import os
import json
import openai
import sqlite3
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()
openai.api_key = os.getenv("OPENAI_API_KEY")
client = OpenAI()

MODEL = "gpt-4.1-2025-04-14"
DATABASE = "db/bnpl.db"

database_schema_string = """
Table: transactions
Columns: transaction_id, customer_id, merchant, category, purchase_amount, installment_count, installment_amount, purchase_date, final_due_date, status, credit_score, risk_score, late_fee, default_flag
"""

tools = [
    {
        "type": "function",
        "name": "bnpl_database_query",
        "description": "Get an answer from the BNPL SQL database based on a query.",
        "parameters": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": f"""
                        Generate an SQL query using the schema:
                        {database_schema_string}

                        IMPORTANT RULES:
                        - Use single quotes in SQL normally, like 'Electronics'
                        - DO NOT escape quotes (no backslashes)
                        - Output only raw SQL, not JSON, not Python code
                        - Do not wrap the SQL in quotes
""",
                }
            },
            "required": ["query"],
        },
    },
]

def bnpl_database_query(query):
    try:
        conn = sqlite3.connect(DATABASE)
        # print("Executing query: ", query)
        results = conn.execute(query).fetchall()
        # print("Query results: ", results)
        return results
    except Exception as e:
        raise Exception(f"SQL error: {e}")

messages = [
    {"role": "user", "content": "What is the average purchase amount for transactions in the 'Electronics' category?"}
]

response = client.responses.create(
    model=MODEL,
    tools=tools,
    input=messages,
)

for item in response.output:
    if item.type == "function_call":
        if item.name == "bnpl_database_query":

            # Parse arguments (they come as a string)
            args = json.loads(item.arguments)

            db_results = bnpl_database_query(args["query"])

            messages.append({
                "role": "assistant",
                "content": str(db_results)
            })
# print("Messages: ", messages)

response = client.responses.create(
    model=MODEL,
    instructions="Respond to the initial user question with a database result generated by a tool. Use markdown formatting.",
    input=messages,
)

print("Final output: " + response.output_text)